name: "Web Deploy"
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  NODE_ENV: production

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  web-build:
    name: Web build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - run: npm ci --include=dev
      - run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "dist"
  web-deploy:
    name: Web deploy
    runs-on: ubuntu-latest
    needs: web-build
    environment:
      name: github-pages
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
